<a href="https://colab.research.google.com/github/youssef1234-pixel/Python_tutorials/blob/main/Copy_of_Task_12numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
import numpy as np
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
Z.size * Z.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:

import numpy as np
Z = np.arange(9).reshape(3,3)
Z


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
import numpy as np
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:

import numpy as np
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:

import numpy as np
Z = np.random.random((3,3,3))
Z

array([[[0.0876325 , 0.11032073, 0.16214173],
        [0.68097678, 0.35477987, 0.39356121],
        [0.88591671, 0.37445728, 0.104938  ]],

       [[0.66853582, 0.35557821, 0.82431201],
        [0.32389931, 0.82647564, 0.26193835],
        [0.91837003, 0.41069855, 0.28371105]],

       [[0.90871172, 0.09076584, 0.66489655],
        [0.99515356, 0.24883104, 0.19980677],
        [0.97860039, 0.12361115, 0.71580826]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:

import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0035970798792236414 0.9999961330418077


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
import numpy as np

Z = np.random.random(30)
m = Z.mean()
m

np.float64(0.4506151706834899)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:

import numpy as np

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:

import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:

import numpy as np
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:

import numpy as np
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:

shape = (6, 7, 8)
index_1d = 99

x = index_1d // (shape[1] * shape[2])
remaining_index = index_1d % (shape[1] * shape[2])
y = remaining_index // shape[2]
z = remaining_index % shape[2]

print(f"The index of the 100th element is ({x},{y},{z})")

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
import numpy as np
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / np.std(Z)
Z

array([[-0.76991268, -0.30024323,  1.26576092,  0.80986268, -1.77959518],
       [ 0.40191915,  0.58872658,  0.30223397,  0.27484502, -1.09128792],
       [-0.40359624,  0.8283771 , -0.63790223,  1.71073738, -0.89368218],
       [-0.62153448, -1.36356588,  1.42283734, -0.07100373,  1.00335049],
       [-1.70846393, -0.80784048,  0.16963761, -0.10498266,  1.77532258]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
A = np.random.rand(5,3)
B = np.random.rand(3,2)
C = np.dot(A, B)
C

array([[1.78339841, 0.53132454],
       [0.75694831, 0.24049908],
       [0.992867  , 0.14600866],
       [0.66315632, 0.36936367],
       [0.75017652, 0.33358146]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np
Z = np.arange(11)
Z[(Z > 3) & (Z < 8)] *= -1
Z

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
from numpy import *
print(sum(range(5),-1))
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
print("Z**Z is legal")
print("2 << Z >> 2 is legal")
print("Z <- Z is  not legal") # This is a comparison, not assignment in Python/Numpy context
print("1j*Z is legal")
print("Z/1/1 is legal")
print("Z<Z>Z is illegal")

Z**Z is legal
2 << Z >> 2 is legal
Z <- Z is  not legal
1j*Z is legal
Z/1/1 is legal
Z<Z>Z is illegal


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [1]:


import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


/tmp/ipython-input-1-3875147493.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-1-3875147493.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-1-3875147493.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [2]:
import numpy as np
print(np.copysign(np.ceil(np.abs(Z)), Z))


NameError: name 'Z' is not defined

#### 30. How to find common values between two arrays? (★☆☆)

In [3]:
import numpy as np
np.intersect1d(np.array([1, 3, 5]), np.array([3, 4, 5, 6]))

array([3, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [4]:
import warnings
warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [5]:
import numpy as np
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
from datetime import datetime, timedelta

today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2025-06-25
Today: 2025-06-26
Tomorrow: 2025-06-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates_july_2016

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [7]:
import numpy as np
A = np.ones(3)
B = np.ones(3)*2

# Compute A + B in place in A
np.add(A, B, out=A)

# Compute -A/2 in place in B
np.divide(A, -2, out=B)

# Compute A * B in place in A
np.multiply(A, B, out=A)

A

array([-4.5, -4.5, -4.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [8]:
import numpy as np
Z = np.random.uniform(0, 10, 10)
print(Z)

# Method 1: Type casting
print("Method 1: Type Casting")
print(Z.astype(int))

# Method 2: Floor function
print("Method 2: Floor function")
print(np.floor(Z))

# Method 3: Truncate function
print("Method 3: Truncate function")
print(np.trunc(Z))

# Method 4: Integer division with 1
print("Method 4: Integer division with 1")
print(Z // 1)


[4.54665193 2.03127535 7.93962137 1.72499952 7.72870648 8.3263121
 4.2709503  5.94644976 9.19792538 4.35946169]
Method 1: Type Casting
[4 2 7 1 7 8 4 5 9 4]
Method 2: Floor function
[4. 2. 7. 1. 7. 8. 4. 5. 9. 4.]
Method 3: Truncate function
[4. 2. 7. 1. 7. 8. 4. 5. 9. 4.]
Method 4: Integer division with 1
[4. 2. 7. 1. 7. 8. 4. 5. 9. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [9]:
import numpy as np
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [11]:
import numpy as np
def generate_integers():
  for i in range(10):
    yield i

integer_array = np.fromiter(generate_integers(), dtype=int)
print(integer_array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
import numpy as np
Z = np.linspace(0,1,12)[1:-1]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [12]:
import numpy as np
Z = np.random.random(10)
Z.sort()
Z

array([0.05257443, 0.1006114 , 0.28370449, 0.29595646, 0.32651509,
       0.38949024, 0.65428041, 0.7651825 , 0.82993932, 0.97812598])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [14]:
import numpy as np

small_array = np.arange(5)

sum(small_array)

np.int64(10)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [15]:
import numpy as np
A = np.random.rand(5)
B = np.random.rand(5)

are_equal = np.array_equal(A, B)
print(f"Are arrays A and B equal? {are_equal}")

Are arrays A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [18]:


import numpy as np
Z = np.zeros(10)
Z.flags.writeable = False
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [19]:
import numpy as np
Z = np.random.random((10, 2))

# Extract x and y coordinates
x, y = Z[:, 0], Z[:, 1]

# Calculate radius (r)
r = np.sqrt(x**2 + y**2)

# Calculate angle (theta) using arctan2 (handles quadrants correctly)
theta = np.arctan2(y, x)

# Combine into a 10x2 matrix representing polar coordinates (r, theta)
polar_coordinates = np.stack((r, theta), axis=1)

polar_coordinates

array([[1.102806  , 0.84369375],
       [0.96783078, 1.41455145],
       [1.00510061, 0.26399504],
       [1.09586513, 0.86514494],
       [0.40093749, 0.91335292],
       [0.87259883, 0.18953729],
       [0.58916753, 1.00727648],
       [0.97208459, 1.27211934],
       [0.81099527, 0.25151268],
       [1.06321007, 0.64610718]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [20]:
import numpy as np
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.43656618, 0.62332788, 0.18859048, 0.33121895, 0.76098763,
       0.57297496, 0.17358896, 0.27083365, 0.        , 0.67945922])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [21]:
import numpy as np
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
import numpy as np
X = np.arange(10)
Y = X + 0.5
C = 1.0 / (X[:, np.newaxis] - Y)
C

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [22]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min, np.finfo(dtype).max)


-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [23]:
import numpy as np
np.set_printoptions(threshold=np.inf)
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [24]:
import numpy as np
Z = np.arange(100)
v = np.random.uniform(0,100)


index = (np.abs(Z - v)).argmin()


closest_value = Z[index]

print(f"Original vector Z: {Z}")
print(f"Scalar v: {v}")
print(f"Index of the closest value: {index}")
print(f"Closest value in Z to {v}: {closest_value}")

Original vector Z: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Scalar v: 70.31138313703076
Index of the closest value: 70
Closest value in Z to 70.31138313703076: 70


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [25]:
import numpy as np
position_color = np.zeros(1, dtype=[('position', [('x', float), ('y', float)]),
                                   ('color', [('r', float), ('g', float), ('b', float)])])

position_color

array([((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [26]:
import numpy as np
X = np.random.rand(100, 2)
Y = np.random.rand(100, 2)

distances = np.sqrt(np.sum((X - Y)**2, axis=1))
print("Distances using broadcasting:", distances)

try:
    from scipy.spatial.distance import cdist
    distances_scipy = cdist(X, Y, 'euclidean').diagonal()
    print("Distances using cdist:", distances_scipy)
except ImportError:
    print("Scipy not installed. Skipping cdist example.")
    print("To install scipy, run: !pip install scipy")


diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
pairwise_squared_distances = np.sum(diff**2, axis=-1)
pairwise_distances = np.sqrt(pairwise_squared_distances)

# Extract the diagonal for point-by-point distances
point_by_point_distances_pairwise = np.diag(pairwise_distances)
print("Point-by-point distances using pairwise calculation:", point_by_point_distances_pairwise)

Distances using broadcasting: [0.62815349 0.71390311 0.97508752 0.53581231 0.65972637 0.79993946
 0.23761144 0.45026769 1.22999086 0.88136401 0.37740151 0.02519154
 0.52614007 0.15846398 0.5333057  0.33646196 0.2441467  0.17343482
 0.38576524 0.30082771 0.08800434 0.46104819 0.87614555 0.24720941
 0.77359629 0.51467316 0.69014205 0.36788872 0.51525355 0.33524753
 0.78126175 0.29634511 0.65546096 0.38692331 0.31644501 0.80034707
 0.44426443 0.53972626 0.16828575 0.26774692 0.28769646 0.33580462
 0.57927741 0.13579542 0.9182506  0.31087303 0.71660149 0.55696029
 0.77719387 0.59890408 0.22405563 0.48880582 0.45415021 0.42096821
 0.7590137  0.55968008 0.43343179 0.63805111 0.20287846 0.47118202
 0.72956649 0.3609576  0.66682948 0.19762433 0.6814276  0.17504187
 0.45081884 0.19214563 0.93117316 0.3517478  0.9353214  0.27614438
 0.17703326 0.70785193 0.7823474  0.36903385 0.71788391 0.74935011
 0.40112682 0.27810319 0.56348289 0.81100407 1.03085467 0.4104
 0.4095549  0.55913439 0.14063166 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [27]:
import numpy as np
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)

# View the float array as an integer array in place
Z_int_view = Z.view(np.int32)
print(Z_int_view)

[ 5.9744663 28.66175   41.088795  38.39728   35.190205  93.408516
 45.951668  91.99648   57.391132  22.002554 ]
[1086271188 1105546052 1109678829 1108973265 1108132549 1119539497
 1110953602 1119354419 1113952389 1102054715]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
import numpy as np
filename = 'data.txt'

# Create the file with the given content
with open(filename, 'w') as f:
  f.write('1, 2, 3, 4, 5\n')
  f.write('6,  ,  , 7, 8\n')
  f.write(' ,  , 9,10,11\n')

data = np.genfromtxt(filename, delimiter=',', dtype=np.float64)
data

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [28]:
import numpy as np
# Method 1: Using np.ndenumerate
Z = np.arange(10).reshape(2, 5)
print("Using np.ndenumerate:")
for index, value in np.ndenumerate(Z):
  print(f"Index: {index}, Value: {value}")

# Method 2: Using np.ndindex
print("\nUsing np.ndindex:")
for index in np.ndindex(Z.shape):
  print(f"Index: {index}, Value: {Z[index]}")

# Method 3: Using a flat iterator and enumerate
print("\nUsing a flat iterator and enumerate:")
for index, value in enumerate(Z.flatten()):
  # Convert 1D index back to multi-dimensional index if needed
  multi_index = np.unravel_index(index, Z.shape)
  print(f"Index: {multi_index}, Value: {value}")



Using np.ndenumerate:
Index: (0, 0), Value: 0
Index: (0, 1), Value: 1
Index: (0, 2), Value: 2
Index: (0, 3), Value: 3
Index: (0, 4), Value: 4
Index: (1, 0), Value: 5
Index: (1, 1), Value: 6
Index: (1, 2), Value: 7
Index: (1, 3), Value: 8
Index: (1, 4), Value: 9

Using np.ndindex:
Index: (0, 0), Value: 0
Index: (0, 1), Value: 1
Index: (0, 2), Value: 2
Index: (0, 3), Value: 3
Index: (0, 4), Value: 4
Index: (1, 0), Value: 5
Index: (1, 1), Value: 6
Index: (1, 2), Value: 7
Index: (1, 3), Value: 8
Index: (1, 4), Value: 9

Using a flat iterator and enumerate:
Index: (np.int64(0), np.int64(0)), Value: 0
Index: (np.int64(0), np.int64(1)), Value: 1
Index: (np.int64(0), np.int64(2)), Value: 2
Index: (np.int64(0), np.int64(3)), Value: 3
Index: (np.int64(0), np.int64(4)), Value: 4
Index: (np.int64(1), np.int64(0)), Value: 5
Index: (np.int64(1), np.int64(1)), Value: 6
Index: (np.int64(1), np.int64(2)), Value: 7
Index: (np.int64(1), np.int64(3)), Value: 8
Index: (np.int64(1), np.int64(4)), Value: 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [29]:
import numpy as np
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
G


array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [30]:
import numpy as np

n_rows = 5
n_cols = 5
p = 10

Z = np.zeros((n_rows, n_cols), dtype=int)


total_elements = n_rows * n_cols


flat_indices = np.arange(total_elements)


selected_flat_indices = np.random.choice(flat_indices, size=p, replace=False)


row_indices, col_indices = np.unravel_index(selected_flat_indices, (n_rows, n_cols))


Z[row_indices, col_indices] = 1

Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 1, 1]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [31]:
# prompt: Subtract the mean of each row of a matrix

import numpy as np
X = np.random.rand(5, 10)

# Method 1: Using broadcasting
mean_of_rows = X.mean(axis=1, keepdims=True)
X_centered = X - mean_of_rows
print("Using broadcasting:\n", X_centered)

# Verification
print("\nMeans of centered rows (should be close to zero):", X_centered.mean(axis=1))


Using broadcasting:
 [[ 0.02834352  0.03946188 -0.19578325  0.44597058 -0.37106803 -0.43335702
   0.31879442  0.02037877  0.40441475 -0.25715564]
 [ 0.42054801 -0.16955995 -0.00167211 -0.0909269  -0.09249063 -0.30015278
   0.60029206 -0.12198773 -0.15669339 -0.08735658]
 [ 0.08107256  0.43301971  0.42709816 -0.06274257  0.19294178  0.20401618
  -0.30611933 -0.38476207 -0.20079608 -0.38372835]
 [-0.07832718 -0.52211303 -0.50767157  0.03621739  0.29366248  0.27735724
   0.1606853   0.38138682  0.36164596 -0.40284341]
 [ 0.02131338  0.1121304  -0.30370167  0.05737883 -0.52807773  0.08964828
   0.02288735  0.01205175  0.21291752  0.30345189]]

Means of centered rows (should be close to zero): [-4.44089210e-17  0.00000000e+00  6.66133815e-17  4.44089210e-17
  1.44328993e-16]


#### 59. How to sort an array by the nth column? (★★☆)

In [32]:


import numpy as np
Z = np.random.randint(0, 100, size=(5, 3))
print("Original array:\n", Z)

n = 1
sorted_indices = np.argsort(Z[:, n])


sorted_array = Z[sorted_indices]

print(f"\nSorted array by column {n}:\n", sorted_array)

Original array:
 [[59 46 68]
 [ 8 39 14]
 [20 35 16]
 [37 85 33]
 [67 26 18]]

Sorted array by column 1:
 [[67 26 18]
 [20 35 16]
 [ 8 39 14]
 [59 46 68]
 [37 85 33]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [33]:


import numpy as np
def has_null_columns(arr):

    # Check if the array has any NaN values
    if not np.isnan(arr).any():
        return False


    return np.isnan(arr).all(axis=0).any()

arr_with_null_column = np.array([[1, 2, np.nan],
                                [4, 5, np.nan],
                                [7, 8, np.nan]])


arr_without_null_column = np.array([[1, 2, 3],
                                   [4, 5, 6],
                                   [7, 8, 9]])


arr_with_some_nan = np.array([[1, 2, np.nan],
                             [4, np.nan, 6],
                             [7, 8, 9]])

print("Array with a null column:\n", arr_with_null_column)
print("Has null columns:", has_null_columns(arr_with_null_column))

print("\nArray without null columns:\n", arr_without_null_column)
print("Has null columns:", has_null_columns(arr_without_null_column))

print("\nArray with some NaNs but no entirely null columns:\n", arr_with_some_nan)
print("Has null columns:", has_null_columns(arr_with_some_nan))


Array with a null column:
 [[ 1.  2. nan]
 [ 4.  5. nan]
 [ 7.  8. nan]]
Has null columns: True

Array without null columns:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Has null columns: False

Array with some NaNs but no entirely null columns:
 [[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
Has null columns: False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [34]:
import numpy as np
v = 0.5

index = (np.abs(Z - v)).argmin()
closest_value = Z[index]

print(f"Original array Z: {Z}")
print(f"Given value v: {v}")
print(f"Index of the nearest value: {index}")
print(f"Nearest value in Z to {v}: {closest_value}")

Original array Z: [[59 46 68]
 [ 8 39 14]
 [20 35 16]
 [37 85 33]
 [67 26 18]]
Given value v: 0.5
Index of the nearest value: 3
Nearest value in Z to 0.5: [37 85 33]


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [35]:


import numpy as np
A = np.array([[1, 2, 3]])
B = np.array([[4], [5], [6]])

print("Shape of A:", A.shape)
print("Shape of B:", B.shape)


result = np.zeros_like(A + B)


it = np.nditer([A, B, result],
               flags=['external_loop', 'buffered'],
               op_flags=[['readonly'], ['readonly'], ['writeonly']])

for x, y, z in it:
  z[...] = x + y

print("\nResult of the sum using iterator:\n", result)


print("\nResult of direct sum:\n", A + B)

Shape of A: (1, 3)
Shape of B: (3, 1)

Result of the sum using iterator:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]

Result of direct sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
import numpy as np
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', "Unnamed")


my_array = NamedArray(np.arange(5), name="My Awesome Array")
print(my_array)
print(my_array.name)

another_array = NamedArray(np.random.rand(3,3))
print(another_array)
another_array.name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [36]:
import numpy as np
Z = np.zeros(10)
indices = np.array([0, 1, 2, 2, 3, 3, 3])
np.add.at(Z, indices, 1)
print("Method 1 (np.add.at):", Z)

Method 1 (np.add.at): [1. 1. 2. 3. 0. 0. 0. 0. 0. 0.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [37]:
import numpy as np
X = np.array([1, 2, 3, 4, 5, 6])
I = np.array([0, 1, 2, 0, 1, 2])
F = np.zeros(3)

np.add.at(F, I, X)

print("Vector X:", X)
print("Index list I:", I)
print("Accumulated array F:", F)


Vector X: [1 2 3 4 5 6]
Index list I: [0 1 2 0 1 2]
Accumulated array F: [5. 7. 9.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [39]:
import numpy as np

w, h = 100, 100
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.ubyte)
pixels = image.reshape(-1, 3)
unique_colors = np.unique(pixels, axis=0)

# The number of unique colors is the number of rows in the unique_colors array
num_unique_colors = len(unique_colors)

print(f"The number of unique colors in the image is: {num_unique_colors}")

The number of unique colors in the image is: 9998


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [40]:
import numpy as np
X = np.random.rand(2, 3, 4, 5)

# Method 1: Using `axis` tuple
sum_over_last_two = X.sum(axis=(-2, -1))  # or axis=(2, 3)

print("Original shape:", X.shape)
print("Shape after summing over last two axes:", sum_over_last_two.shape)


Original shape: (2, 3, 4, 5)
Shape after summing over last two axes: (2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [41]:
# prompt: Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

import numpy as np
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 0, 1, 1, 0, 2, 2, 1, 0, 2])

# Method 1: Using numpy's bincount
# Compute the sum for each subset index
sums = np.bincount(S, weights=D)
# Count the number of elements in each subset
counts = np.bincount(S)

# Avoid division by zero for indices that don't appear in S
means = sums / counts
print("Method 1 (bincount):", means)


Method 1 (bincount): [4.25       5.         7.66666667]


#### 69. How to get the diagonal of a dot product? (★★★)

In [42]:
import numpy as np

A = np.random.rand(3, 4)
B = np.random.rand(4, 3)
dot_product = np.dot(A, B)
diagonal_of_dot_product = np.diag(dot_product)
print("Method 1 (Full dot product then diagonal):\n", diagonal_of_dot_product)


Method 1 (Full dot product then diagonal):
 [1.05138054 0.46314499 1.040523  ]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [43]:
import numpy as np
Z = np.array([1, 2, 3, 4, 5])
num_zeros = 3
new_size = len(Z) + (len(Z) - 1) * num_zeros

new_vector = np.zeros(new_size, dtype=Z.dtype)
new_vector[::num_zeros + 1] = Z
new_vector

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [44]:
import numpy as np
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)
result = A * B[:, :, np.newaxis]
print("Method 1 (Broadcasting) shape:", result.shape)

Method 1 (Broadcasting) shape: (5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [45]:
import numpy as np
Z = np.arange(25).reshape(5,5)
print("Original array:\n", Z)

# Swap row 1 (index 1) and row 3 (index 3)
i, j = 1, 3
Z[[i, j]] = Z[[j, i]]

print(f"\nArray after swapping row {i} and row {j}:\n", Z)

Original array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Array after swapping row 1 and row 3:
 [[ 0  1  2  3  4]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [46]:


import numpy as np
triangles = np.random.randint(0,100,(10,3))
edges = np.concatenate([triangles[:,[0,1]],
                        triangles[:,[1,2]],
                        triangles[:,[2,0]]])

edges.sort(axis=1)

unique_segments = np.unique(edges, axis=0)
print("Method 1 (Manual edge extraction and sorting):\n", unique_segments)

Method 1 (Manual edge extraction and sorting):
 [[ 7 14]
 [ 7 33]
 [ 7 45]
 [ 7 49]
 [10 36]
 [10 49]
 [10 73]
 [10 78]
 [14 45]
 [15 63]
 [15 85]
 [24 86]
 [24 99]
 [31 40]
 [31 83]
 [31 87]
 [31 94]
 [33 49]
 [33 70]
 [33 72]
 [36 49]
 [40 83]
 [57 63]
 [57 65]
 [63 65]
 [63 85]
 [70 72]
 [73 78]
 [86 99]
 [87 94]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
import numpy as np
C = np.array([0, 1, 0, 2, 0, 3, 0, 2, 0, 1])
A = np.repeat(np.arange(len(C)), C)
print("Original bincount array C:", C)
print("Constructed array A:", A)
print("Bincount of A:", np.bincount(A))

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [47]:
import numpy as np
def moving_average(arr, window_size):
    weights = np.ones(window_size) / window_size
    return np.convolve(arr, weights, mode='valid')

# Example usage:
data = np.arange(10)
window_size = 3
averages = moving_average(data, window_size)
print("Original data:", data)
print(f"Moving averages with window size {window_size}:", averages)

data_float = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
window_size_float = 2
averages_float = moving_average(data_float, window_size_float)
print("\nOriginal data (float):", data_float)
print(f"Moving averages with window size {window_size_float}:", averages_float)

Original data: [0 1 2 3 4 5 6 7 8 9]
Moving averages with window size 3: [1. 2. 3. 4. 5. 6. 7. 8.]

Original data (float): [1. 2. 3. 4. 5. 6.]
Moving averages with window size 2: [1.5 2.5 3.5 4.5 5.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [48]:
import numpy as np
Z = np.arange(10)
window_size = 3
stride = 1
# Calculate the number of rows in the resulting array
# The number of rows is (length of Z - window size) / stride + 1
num_rows = (len(Z) - window_size) // stride + 1

# Create the 2D array
result_array = np.lib.stride_tricks.as_strided(
    Z,
    shape=(num_rows, window_size),
    strides=(Z.strides[0] * stride, Z.strides[0])
)

print("Original 1D array Z:", Z)
print("\nResulting 2D array with sliding window:\n", result_array)

Original 1D array Z: [0 1 2 3 4 5 6 7 8 9]

Resulting 2D array with sliding window:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:

import numpy as np


P0 = np.array(P0)
P1 = np.array(P1)
P = np.array(P)

# Calculate the vector representing each line (P1 - P0)
line_vectors = P1 - P0 # Shape: (num_lines, 2)

# Calculate the squared length of each line vector (denominator squared)
line_lengths_sq = np.sum(line_vectors**2, axis=1) # Shape: (num_lines,)


line_lengths_sq[line_lengths_sq == 0] = 1e-8 # or handle this case differently


line_lengths = np.sqrt(line_lengths_sq) # Shape: (num_lines,)

line_vectors = line_vectors[:, np.newaxis, :] # Shape: (num_lines, 1, 2)
P_reshaped = P[np.newaxis, :, :]          # Shape: (1, num_points, 2)
P0_reshaped = P0[:, np.newaxis, :]        # Shape: (num_lines, 1, 2)

point_vectors = P_reshaped - P0_reshaped # Shape: (num_lines, num_points, 2)


numerator = np.abs(line_vectors[:, :, 0] * point_vectors[:, :, 1] - line_vectors[:, :, 1] * point_vectors[:, :, 0]) # Shape: (num_lines, num_points)


line_lengths_reshaped = line_lengths[:, np.newaxis] # Shape: (num_lines, 1)


distances = numerator / line_lengths_reshaped # Shape: (num_lines, num_points)


distances

NameError: name 'P0' is not defined

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:

import numpy as np
def extract_subpart(arr, center, shape, fill_value=0):

    arr_shape = arr.shape
    ndim = len(arr_shape)
    sub_arr = np.full(shape, fill_value, dtype=arr.dtype)


    start_indices_arr = []
    end_indices_arr = []
    start_indices_sub = []
    end_indices_sub = []

    for i in range(ndim):
        center_i = center[i]
        shape_i = shape[i]
        arr_shape_i = arr_shape[i]


        start_relative = center_i - shape_i // 2
        end_relative = start_relative + shape_i


        start_arr = max(0, start_relative)
        end_arr = min(arr_shape_i, end_relative)


        start_sub = max(0, -start_relative)
        end_sub = start_sub + (end_arr - start_arr)

        start_indices_arr.append(start_arr)
        end_indices_arr.append(end_arr)
        start_indices_sub.append(start_sub)
        end_indices_sub.append(end_sub)


    slice_arr = tuple(slice(start_indices_arr[i], end_indices_arr[i]) for i in range(ndim))
    slice_sub = tuple(slice(start_indices_sub[i], end_indices_sub[i]) for i in range(ndim))


    sub_arr[slice_sub] = arr[slice_arr]

    return sub_arr


arr = np.arange(25).reshape(5, 5)
print("Original array:")
print(arr)


center = (2, 2)
shape = (3, 3)
fill_value = -1


subpart = extract_subpart(arr, center, shape, fill_value)
print("\nExtracted subpart (centered at (2,2), shape (3,3), fill -1):")
print(subpart)


center = (0, 0)
shape = (3, 3)
subpart_padded = extract_subpart(arr, center, shape, fill_value)
print("\nExtracted subpart (centered at (0,0), shape (3,3), fill -1):")
print(subpart_padded)


center = (4, 4)
shape = (3, 3)
subpart_edge = extract_subpart(arr, center, shape, fill_value)
print("\nExtracted subpart (centered at (4,4), shape (3,3), fill -1):")
print(subpart_edge)


center = (1, 3)
shape = (4, 2)
subpart_diff = extract_subpart(arr, center, shape, fill_value)
print("\nExtracted subpart (centered at (1,3), shape (4,2), fill -1):")
print(subpart_diff)


arr_3d = np.arange(2*3*4).reshape(2, 3, 4)
print("\nOriginal 3D array:")
print(arr_3d)
center_3d = (0, 1, 2)
shape_3d = (2, 2, 3)
subpart_3d = extract_subpart(arr_3d, center_3d, shape_3d, fill_value)
print("\nExtracted 3D subpart (centered at (0,1,2), shape (2,2,3), fill -1):")
print(subpart_3d)


Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


AxisError: axis 1 is out of bounds for array of dimension 0

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:

import numpy as np
Z = np.arange(1, 15)
window_size = 4
R = np.array([Z[i:i+window_size] for i in range(len(Z) - window_size + 1)])
R

#### 82. Compute a matrix rank (★★★)

In [ ]:

import numpy as np
np.linalg.matrix_rank(Z)

#### 83. How to find the most frequent value in an array?

In [ ]:


import numpy as np
from collections import Counter

Z = np.array([1, 2, 2, 3, 4, 2, 1, 5, 5, 5])
counts = Counter(Z)
most_common_value = counts.most_common(1)[0][0]
print(f"The most frequent value is: {most_common_value}")


counts = np.bincount(Z)
most_common_value_np = np.argmax(counts)
print(f"The most frequent value (using bincount) is: {most_common_value_np}")

The most frequent value is: 2
The most frequent value (using bincount) is: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:


import numpy as np
n = 10
mat = np.random.randint(0,10,(n,n))
size = 3
blocks = []
for i in range(n - size + 1):
    for j in range(n - size + 1):
        block = mat[i:i+size, j:j+size]
        blocks.append(block)



print(f"Number of 3x3 blocks: {len(blocks)}")


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:


import numpy as np
class SymmetricMatrix(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        if i != j:
            super().__setitem__((j, i), value)


Z = np.zeros((5, 5)).view(SymmetricMatrix)
Z[1, 3] = 10
print(Z)
Z[0, 4] = 5
Z

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


SymmetricMatrix([[ 0.,  0.,  0.,  0.,  5.],
                 [ 0.,  0.,  0., 10.,  0.],
                 [ 0.,  0.,  0.,  0.,  0.],
                 [ 0., 10.,  0.,  0.,  0.],
                 [ 5.,  0.,  0.,  0.,  0.]])

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:

import numpy as np

p = 5
n = 4


matrices = np.random.rand(p, n, n)


vectors = np.random.rand(p, n, 1)


sum_of_products = np.einsum('pij,pik->pi', matrices, vectors).sum(axis=0).reshape(n, 1)

print(f"Shape of matrices: {matrices.shape}")
print(f"Shape of vectors: {vectors.shape}")
print(f"Shape of the sum of products: {sum_of_products.shape}")


Shape of matrices: (5, 4, 4)
Shape of vectors: (5, 4, 1)
Shape of the sum of products: (4, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:


import numpy as np

Z = np.arange(16*16).reshape(16,16)
block_size = 4

blocks = Z.reshape(16//block_size, block_size, 16//block_size, block_size)


block_sums = blocks.sum(axis=(1, 3))

block_sums

array([[ 408,  472,  536,  600],
       [1432, 1496, 1560, 1624],
       [2456, 2520, 2584, 2648],
       [3480, 3544, 3608, 3672]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
import numpy as np
def update(board):

    rows, cols = board.shape
    new_board = board.copy()

    for i in range(rows):
        for j in range(cols):

            neighborhood = board[max(0, i-1):min(rows, i+2), max(0, j-1):min(cols, j+2)]
            live_neighbors = np.sum(neighborhood) - board[i, j]


            if board[i, j] == 1 and (live_neighbors < 2 or live_neighbors > 3):
                new_board[i, j] = 0
            elif board[i, j] == 0 and live_neighbors == 3:
                new_board[i, j] = 1

    return new_board

def run_game_of_life(initial_board, num_generations):

    board = initial_board.copy()
    for _ in range(num_generations):
        board = update(board)
    return board


initial_board = np.zeros((10, 10), dtype=int)
initial_board[1, 2] = 1
initial_board[2, 3] = 1
initial_board[3, 1:4] = 1

print("Initial Board:")
print(initial_board)


final_board = run_game_of_life(initial_board, 10)

print("\nFinal Board after 10 generations:")
print(final_board)

Initial Board:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


AxisError: axis 2 is out of bounds for array of dimension 0

#### 89. How to get the n largest values of an array (★★★)

In [ ]:


import numpy as np
def n_largest_values(arr, n):

  return np.sort(arr)[-n:]

my_array = np.array([1, 5, 2, 8, 3, 9, 4, 7, 6, 10])
n = 3
largest_values = n_largest_values(my_array, n)
print(f"The {n} largest values are: {largest_values}")

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:

import numpy as np
from itertools import product

def cartesian_product(*vectors):

  return list(product(*vectors))

# Example usage:
vector1 = [1, 2]
vector2 = ['a', 'b']
vector3 = ['x', 'y', 'z']

result = cartesian_product(vector1, vector2, vector3)
print(result)

# Example with numpy arrays (will still return list of tuples)
np_vector1 = np.array([10, 20])
np_vector2 = np.array(['c', 'd'])
np_result = cartesian_product(np_vector1, np_vector2)
print(np_result)


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:


import numpy as np
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
R

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
import numpy as np

Z_cubed_method1 = Z**3
print("Method 1 (element-wise operator):")
print(Z_cubed_method1)


Z_cubed_method2 = np.power(Z, 3)
print("\nMethod 2 (np.power()):")
print(Z_cubed_method2)

Z_cubed_method3 = np.empty_like(Z)
for i in range(len(Z)):
  Z_cubed_method3[i] = Z[i] * Z[i] * Z[i]

print("\nMethod 3 (Manual multiplication - loop):")
print(Z_cubed_method3)


print("\nAre the results of Method 1 and Method 2 close?", np.allclose(Z_cubed_method1, Z_cubed_method2))
print("Are the results of Method 1 and Method 3 close?", np.allclose(Z_cubed_method1, Z_cubed_method3))


Method 1 (element-wise operator):
[[ 1  1 27]
 [27 27 27]
 [27 27  1]
 [ 0 27  8]
 [64 27 27]
 [27 64  8]
 [64  8  0]
 [27  8  1]
 [ 1  8 64]
 [ 1 64  8]]

Method 2 (np.power()):
[[ 1  1 27]
 [27 27 27]
 [27 27  1]
 [ 0 27  8]
 [64 27 27]
 [27 64  8]
 [64  8  0]
 [27  8  1]
 [ 1  8 64]
 [ 1 64  8]]

Method 3 (Manual multiplication - loop):
[[ 1  1 27]
 [27 27 27]
 [27 27  1]
 [ 0 27  8]
 [64 27 27]
 [27 64  8]
 [64  8  0]
 [27  8  1]
 [ 1  8 64]
 [ 1 64  8]]

Are the results of Method 1 and Method 2 close? True
Are the results of Method 1 and Method 3 close? True


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:

import numpy as np
A = np.random.randint(0, 5, size=(8, 3))
B = np.random.randint(0, 5, size=(2, 2))

print("Array A:")
print(A)
print("\nArray B:")
print(B)


A_sorted_rows = np.sort(A, axis=1)
B_sorted_rows = np.sort(B, axis=1)


A_tuple_rows = [tuple(row) for row in A_sorted_rows]
B_tuple_rows = [tuple(row) for row in B_sorted_rows]


matching_indices = []
for i in range(A.shape[0]):
    is_match = True
    for b_row_tuple in B_tuple_rows:
        # Check if all elements of the sorted B row are present in the sorted A row
        if not set(b_row_tuple).issubset(set(A_tuple_rows[i])):
            is_match = False
            break
    if is_match:
        matching_indices.append(i)

print("\nRows of A that contain elements of each row of B:")
print(A[matching_indices])
print("\nIndices of matching rows in A:")
matching_indices

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
import numpy as np

Z = np.random.randint(0,5,(10,3))
print(Z)

unequal_rows_mask = ~np.all(Z == Z[:, [0]], axis=1)
unequal_rows = Z[unequal_rows_mask]
print("\nRows with unequal values:")
unequal_rows

[[3 4 0]
 [4 4 3]
 [3 1 0]
 [4 4 4]
 [3 0 4]
 [2 2 4]
 [3 0 1]
 [4 2 4]
 [4 0 0]
 [0 1 3]]

Rows with unequal values:


array([[3, 4, 0],
       [4, 4, 3],
       [3, 1, 0],
       [3, 0, 4],
       [2, 2, 4],
       [3, 0, 1],
       [4, 2, 4],
       [4, 0, 0],
       [0, 1, 3]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
import numpy as np

Z = np.array([0, 1, 2, 3, 15], dtype=np.uint8)

num_bits = int(np.ceil(np.log2(np.max(Z) + 1)))
binary_matrix = np.unpackbits(Z[:, np.newaxis], axis=1)[:, -num_bits:]
binary_matrix

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
import numpy as np

Z = np.random.randint(0, 5, size=(10, 3))
unique_rows = np.unique(Z, axis=0)
unique_rows

array([[0, 3, 2],
       [1, 1, 3],
       [1, 2, 4],
       [1, 4, 2],
       [3, 2, 1],
       [3, 3, 1],
       [3, 3, 3],
       [3, 4, 2],
       [4, 2, 0],
       [4, 3, 3]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:

import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])


inner_prod_einsum = np.einsum('i,i->', A, B)
print("Inner product (einsum):", inner_prod_einsum)
print("Inner product (dot):", np.dot(A, B))


outer_prod_einsum = np.einsum('i,j->ij', A, B)
print("Outer product (einsum):\n", outer_prod_einsum)
print("Outer product (outer):\n", np.outer(A, B))

sum_einsum_A = np.einsum('i->', A)
print("Sum (einsum for A):", sum_einsum_A)
print("Sum (sum for A):", np.sum(A))


mul_einsum = np.einsum('i,i->i', A, B)
print("Element-wise multiplication (einsum):", mul_einsum)
print("Element-wise multiplication (multiply):", np.multiply(A, B))

Inner product (einsum): 32
Inner product (dot): 32
Outer product (einsum):
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Outer product (outer):
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum (einsum for A): 6
Sum (sum for A): 6
Element-wise multiplication (einsum): [ 4 10 18]
Element-wise multiplication (multiply): [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:


import numpy as np
def sample_equidistant(X, Y, num_samples):

    if len(X) != len(Y):
        raise ValueError("X and Y must have the same length.")
    if num_samples <= 0:
        raise ValueError("Number of samples must be positive.")

    points = np.vstack((X, Y)).T
    distances = np.cumsum(np.sqrt(np.sum(np.diff(points, axis=0)**2, axis=1)))
    distances = np.insert(distances, 0, 0)

    total_distance = distances[-1]
    equidistant_distances = np.linspace(0, total_distance, num_samples)


    x_samples = np.interp(equidistant_distances, distances, X)
    y_samples = np.interp(equidistant_distances, distances, Y)

    return x_samples, y_samples

X = np.array([0, 1, 3, 6, 8])
Y = np.array([0, 2, 2, 4, 1])


num_samples = 10

x_equi, y_equi = sample_equidistant(X, Y, num_samples)

print("Original X:", X)
print("Original Y:", Y)
print("Equidistant X samples:", x_equi)
print("Equidistant Y samples:", y_equi)

Original X: [0 1 3 6 8]
Original Y: [0 2 2 4 1]
Equidistant X samples: [0.         0.56881448 1.3077477  2.57965553 3.70854355 4.76683484
 5.82512613 6.58894495 7.29447247 8.        ]
Equidistant Y samples: [0.         1.13762895 2.         2.         2.47236237 3.17788989
 3.88341742 3.11658258 2.05829129 1.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:

import numpy as np

n = 10
X = np.random.randint(0, n + 5, size=(20, 5))


is_multinomial = (X.dtype == int) & (X.sum(axis=1) == n)

selected_rows = X[is_multinomial]
selected_rows

array([], shape=(0, 5), dtype=int64)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:

import numpy as np
def bootstrap_mean_ci(X, n_bootstraps=1000, ci=95):

  bootstrap_means = []
  n = len(X)
  for _ in range(n_bootstraps):
    sample = np.random.choice(X, size=n, replace=True)
    bootstrap_means.append(np.mean(sample))

  lower_percentile = (100 - ci) / 2
  upper_percentile = 100 - lower_percentile

  lower_bound = np.percentile(bootstrap_means, lower_percentile)
  upper_bound = np.percentile(bootstrap_means, upper_percentile)

  return lower_bound, upper_bound


X = np.random.rand(100)
lower, upper = bootstrap_mean_ci(X)
print(f"Bootstrapped 95% confidence interval for the mean: ({lower:.4f}, {upper:.4f})")

Bootstrapped 95% confidence interval for the mean: (0.4546, 0.5537)
